server:
  port: 8080

spring:
  application:
    name: sriAnuApp
  
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  
  liquibase:
    enabled: false